---
# tasks file for shawly.compose_cleric

- name: Upload compose-cleric.service
  become: true
  ansible.builtin.template:
    src: compose-cleric.service.j2
    dest: "{{ compose_cleric_service_dir }}/compose-cleric.service"
    owner: root
    group: root
    mode: "0644"
  tags:
    - compose_cleric

- name: Create {{ compose_cleric_install_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ compose_cleric_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags:
    - compose_cleric

- name: Upload cleric.sh to {{ compose_cleric_install_dir }}
  become: true
  ansible.builtin.copy:
    src: cleric.sh
    dest: "{{ compose_cleric_install_dir }}/cleric.sh"
    owner: root
    group: root
    mode: "0755"
  notify: Restart compose-cleric.service
  tags:
    - compose_cleric

- name: Enable and start compose-cleric.service
  become: true
  ansible.builtin.service:
    name: compose-cleric
    enabled: true
    state: started
    daemon_reload: true
  register: _compose_cleric_service_enabled
  tags:
    - compose_cleric

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
