---
# handlers file for shawly.compose_cleric

- name: Restart compose-cleric.service
  become: true
  ansible.builtin.service:
    name: compose-cleric.service
    state: restarted
  when: not _compose_cleric_service_enabled.changed
